# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

stages:
  - lint
  - build
  - test
  - coverage
  - release


variables:
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}

  RELEASE_REGISTRY: docker.io
  RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/os2mo-amqp-trigger-calculate-primary

  PYTEST_COV_MODULE: calculate_primary
  PYTEST_COV_FAIL_UNDER: 0


include:
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/autopub.v1.yml
  - project: labs/salt-automation
    file: gitlab-ci-templates/python/pytest-meta.v1.yml
    ref: "feature/52916_ci_caching_v2"
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/docker-build.v1.yml
  - project: labs/salt-automation
    ref: master
    file: /gitlab-ci-templates/common/docker-release.v1.yml


# This is a workaround for a bug causing detached pipelines on MRs
# See: https://gitlab.com/gitlab-org/gitlab/-/issues/34756
#      https://docs.gitlab.com/ee/ci/yaml/#workflowrules-templates
workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
    - if: $CI_MERGE_REQUEST_IID


Pre-commit:
  stage: lint
  interruptible: true
  needs: []
  image: python:3.8
  before_script:
    - apt-get update && apt-get -y install unixodbc-dev freetds-dev unixodbc tdsodbc libkrb5-dev libmariadb-dev
    - pip install --no-cache-dir poetry
    - poetry install
  script:
    - poetry run pre-commit run --all-files

Test:
  extends: .pytest
  before_script:
    - apt-get update && apt-get -y install unixodbc-dev freetds-dev unixodbc tdsodbc libkrb5-dev libmariadb-dev
    - !reference [.pytest, before_script]

Export coverage:
  extends: .export_coverage
  needs: [Test]

Check coverage:
  extends: .check_coverage
  needs: [Test]
