# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
[tool.poetry]
name = "calculate-primary"
version = "0.0.0"  # versioning handled by conventional commits
description = "OS2mo AMQP Trigger for recalculating primary"
authors = ["Magenta <info@magenta.dk>"]
license = "MPL-2.0"
readme = "README.md"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/os2mo-triggers/os2mo-amqp-trigger-calculate-primary"
keywords = ["os2mo", "amqp"]

[tool.poetry.dependencies]
python = "^3.11"
os2mo-data-import = "^6.0.0"
ra-utils = "^1.11.10"
tenacity = "^8.3.0"
fastramqpi = "^9.1.0"
fastapi = "^0.111.0"

[tool.poetry.group.pre-commit.dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
mypy = "^0.942"
pre-commit = "^3.8.0"
reorder-python-imports = "^3.0.1"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
pytest-split = "^0.8.0"
pytest-cov = "^4.0.0"
hypothesis = "^6.103.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode="auto"

[tool.mypy]
python_version = 3.11
warn_return_any = "True"
warn_unused_configs = "True"
check_untyped_defs = "True"
disallow_untyped_defs = "True"
plugins = "pydantic.mypy"

[tool.flake8]
max-line-length = 88
exclude = [
".git", "__pycache__", ".mypy_cache", ".pytest_cache", ".venv", ".gitlab"
]


[tool.poetry.group.dev.dependencies]
ariadne-codegen = {extras = ["subscriptions"], version = "^0.7.1"}

[tool.ariadne-codegen]

target_package_name = "autogenerated_graphql_client"
target_package_path = "calculate_primary/"
client_name = "GraphQLClient"
schema_path = "schema.graphql"  # curl -O http://localhost:5000/graphql/v22/schema.graphql
queries_path = "queries.graphql"
include_all_inputs = false
include_all_enums = false
plugins = [
    # Return values directly when only a single top field is requested
    "ariadne_codegen.contrib.shorter_results.ShorterResultsPlugin",
]
[tool.ariadne-codegen.scalars.DateTime]
type = "datetime.datetime"
[tool.ariadne-codegen.scalars.UUID]
type = "uuid.UUID"
