# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

query _Testing_GetEngagement($uuid: UUID!) {
  engagements(filter: { uuids: [$uuid], from_date: null, to_date: null }) {
    objects {
      validities(start: null, end: null) {
        primary_response {
          validities(start: null, end: null) {
            uuid
          }
        }
        fraction
      }
    }
  }
}

mutation _Testing_CreateEmployee($input: EmployeeCreateInput!) {
  employee_create(input: $input) {
    uuid
  }
}

mutation _Testing_CreateEngagement($input: EngagementCreateInput!) {
  engagement_create(input: $input) {
    uuid
  }
}

mutation _Testing_CreateOrgUnit($input: OrganisationUnitCreateInput!) {
  org_unit_create(input: $input) {
    uuid
  }
}

mutation _Testing_UpdateEngagement($input: EngagementUpdateInput!) {
  engagement_update(input: $input) {
    uuid
  }
}

mutation _Testing_CreateFacet($input: FacetCreateInput!) {
  facet_create(input: $input) {
    uuid
  }
}

mutation _Testing_CreateClass($input: ClassCreateInput!) {
  class_create(input: $input) {
    uuid
  }
}
