# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import uuid
from datetime import datetime
from typing import AsyncIterator
from uuid import UUID

import pytest
import structlog
from fastapi.applications import FastAPI
from httpx import AsyncClient
from zoneinfo import ZoneInfo

from calculate_primary.app import create_app
from calculate_primary.autogenerated_graphql_client import ClassCreateInput
from calculate_primary.autogenerated_graphql_client import EmployeeCreateInput
from calculate_primary.autogenerated_graphql_client import FacetCreateInput
from calculate_primary.autogenerated_graphql_client import GraphQLClient
from calculate_primary.autogenerated_graphql_client import OrganisationUnitCreateInput
from calculate_primary.autogenerated_graphql_client import RAValidityInput
from calculate_primary.autogenerated_graphql_client import TestingCreateClassClassCreate
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from calculate_primary.autogenerated_graphql_client import TestingCreateFacetFacetCreate
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)
from calculate_primary.autogenerated_graphql_client import ValidityInput

logger = structlog.stdlib.get_logger()


@pytest.fixture
async def app(primary_types: dict[str, UUID]) -> FastAPI:
    # primary_types is needed because `create_app` runs some graphql queries
    # at startup, and expects there to be certain classes
    app = create_app()
    return app


@pytest.fixture
async def graphql_client(mo_client: AsyncClient) -> AsyncIterator[GraphQLClient]:
    graphql_client = GraphQLClient(
        url=f"{mo_client.base_url}/graphql/v22", http_client=mo_client
    )
    async with graphql_client as client:
        yield client


@pytest.fixture
async def default_org_unit(
    graphql_client: GraphQLClient,
) -> TestingCreateOrgUnitOrgUnitCreate:
    tz = ZoneInfo("Europe/Copenhagen")
    long_time_ago = datetime(1970, 1, 1, tzinfo=tz)

    return await graphql_client._testing__create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(from_=long_time_ago),
            name="E Corp",
            org_unit_type=uuid.uuid4(),
        )
    )


@pytest.fixture
async def default_employee(
    graphql_client: GraphQLClient,
) -> TestingCreateEmployeeEmployeeCreate:
    return await graphql_client._testing__create_employee(
        EmployeeCreateInput(
            given_name="Gneurshk",
            surname="Gronk",
        )
    )


@pytest.fixture
async def engagement_type_facet(
    graphql_client: GraphQLClient,
) -> TestingCreateFacetFacetCreate:
    return await graphql_client._testing__create_facet(
        FacetCreateInput(user_key="engagement_type", validity=ValidityInput())
    )


@pytest.fixture
async def default_engagement_type(
    graphql_client: GraphQLClient,
    engagement_type_facet: TestingCreateFacetFacetCreate,
) -> TestingCreateClassClassCreate:
    return await graphql_client._testing__create_class(
        ClassCreateInput(
            name="Employed",
            user_key="Employed",
            facet_uuid=engagement_type_facet.uuid,
            validity=ValidityInput(),
        )
    )


@pytest.fixture
async def primary_type_facet(
    graphql_client: GraphQLClient,
) -> TestingCreateFacetFacetCreate:
    return await graphql_client._testing__create_facet(
        FacetCreateInput(user_key="primary_type", validity=ValidityInput())
    )


@pytest.fixture
async def primary_types(
    graphql_client: GraphQLClient, primary_type_facet: TestingCreateFacetFacetCreate
) -> dict[str, UUID]:
    """
    Creates all the primary types that the various INTEGRATION modes expect.
    """

    user_keys = [
        "primary",
        "non-primary",
        "explicitly-primary",
        "Ansat",
    ]

    primary_types: dict[str, UUID] = {}
    for user_key in user_keys:
        res = await graphql_client._testing__create_class(
            ClassCreateInput(
                name=user_key,
                user_key=user_key,
                facet_uuid=primary_type_facet.uuid,
                validity=ValidityInput(),
            )
        )
        primary_types[user_key] = res.uuid

    return primary_types
