# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import uuid
from datetime import datetime
from typing import Any
from typing import AsyncIterator
from uuid import UUID

import httpx
import pytest
from fastramqpi.config import Settings as FastRAMQPISettings
from httpx import AsyncClient
from zoneinfo import ZoneInfo

from calculate_primary.autogenerated_graphql_client import EmployeeCreateInput
from calculate_primary.autogenerated_graphql_client import GraphQLClient
from calculate_primary.autogenerated_graphql_client import OrganisationUnitCreateInput
from calculate_primary.autogenerated_graphql_client import RAValidityInput
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)


def _load_settings() -> Any:
    """Load FastRAMQPI settings with the FASTRAMQPI__ env prefix.

    Replicates the private `_settings` fixture from fastramqpi.pytest_plugin so
    we can read the same values inside our `mo_client` override.
    """

    class _Settings(FastRAMQPISettings):
        class Config:
            env_prefix = "FASTRAMQPI__"

    return _Settings()


@pytest.fixture
async def mo_client() -> AsyncIterator[AsyncClient]:
    """Authenticated HTTPX client with the OS2mo URL preconfigured.

    Overrides the unauthenticated `mo_client` from fastramqpi.pytest_plugin to
    provide OAuth2 client-credentials authentication, which MO requires.

    The token is fetched manually (rather than via ``AsyncOAuth2Client``) to
    avoid interactions between authlib's internal token-refresh client and
    ``respx``: the auto-use ``passthrough_backing_services`` fixture tears down
    respx *before* ``os2mo_database_snapshot_and_restore`` runs its restore
    request, which would close the transport of a client created by authlib.
    Using a plain ``httpx.AsyncClient`` with a pre-fetched bearer token avoids
    this entirely.
    """
    settings = _load_settings()

    async with httpx.AsyncClient() as token_client:
        resp = await token_client.post(
            f"{settings.auth_server}/realms/{settings.auth_realm}"
            "/protocol/openid-connect/token",
            data={
                "grant_type": "client_credentials",
                "client_id": settings.client_id,
                "client_secret": settings.client_secret.get_secret_value(),
            },
        )
        resp.raise_for_status()
        access_token = resp.json()["access_token"]

    client = AsyncClient(
        base_url=settings.mo_url,
        headers={"Authorization": f"Bearer {access_token}"},
    )
    async with client:
        yield client


@pytest.fixture
async def graphql_client(mo_client: AsyncClient) -> AsyncIterator[GraphQLClient]:
    graphql_client = GraphQLClient(
        url=f"{mo_client.base_url}/graphql/v22", http_client=mo_client
    )
    async with graphql_client as client:
        yield client


@pytest.fixture
async def default_org_unit(
    graphql_client: GraphQLClient,
) -> TestingCreateOrgUnitOrgUnitCreate:
    tz = ZoneInfo("Europe/Copenhagen")
    long_time_ago = datetime(1970, 1, 1, tzinfo=tz)

    return await graphql_client._testing__create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(from_=long_time_ago),
            name="E Corp",
            org_unit_type=uuid.uuid4(),
        )
    )


@pytest.fixture
async def default_employee(
    graphql_client: GraphQLClient,
) -> TestingCreateEmployeeEmployeeCreate:
    return await graphql_client._testing__create_employee(
        EmployeeCreateInput(
            given_name="Gneurshk",
            surname="Gronk",
        )
    )


@pytest.fixture
async def primary_types(graphql_client: GraphQLClient) -> dict[str, UUID]:
    classes = await graphql_client.get_primary_types()
    result: dict[str, UUID] = {}
    for obj in classes.objects:
        for validity in obj.validities:
            result[validity.user_key] = validity.uuid
    return result
