# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import uuid
from datetime import datetime
from typing import AsyncIterator
from uuid import UUID

import pytest
import structlog
from fastapi.applications import FastAPI
from httpx import AsyncClient
from os2mo_helpers.mora_helpers import MoraHelper
from zoneinfo import ZoneInfo

from calculate_primary.app import create_app
from calculate_primary.autogenerated_graphql_client import EmployeeCreateInput
from calculate_primary.autogenerated_graphql_client import GraphQLClient
from calculate_primary.autogenerated_graphql_client import OrganisationUnitCreateInput
from calculate_primary.autogenerated_graphql_client import RAValidityInput
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)
from calculate_primary.config import Settings

logger = structlog.stdlib.get_logger()


@pytest.fixture
async def app() -> FastAPI:
    app = create_app()
    return app


@pytest.fixture
async def graphql_client(mo_client: AsyncClient) -> AsyncIterator[GraphQLClient]:
    graphql_client = GraphQLClient(
        url=f"{mo_client.base_url}/graphql/v22", http_client=mo_client
    )
    async with graphql_client as client:
        yield client


@pytest.fixture
async def default_org_unit(
    graphql_client: GraphQLClient,
) -> TestingCreateOrgUnitOrgUnitCreate:
    tz = ZoneInfo("Europe/Copenhagen")
    long_time_ago = datetime(1970, 1, 1, tzinfo=tz)

    return await graphql_client._testing__create_org_unit(
        OrganisationUnitCreateInput(
            validity=RAValidityInput(from_=long_time_ago),
            name="E Corp",
            org_unit_type=uuid.uuid4(),
        )
    )


@pytest.fixture
async def default_employee(
    graphql_client: GraphQLClient,
) -> TestingCreateEmployeeEmployeeCreate:
    return await graphql_client._testing__create_employee(
        EmployeeCreateInput(
            given_name="Gneurshk",
            surname="Gronk",
        )
    )


@pytest.fixture
async def primary_types(graphql_client: GraphQLClient) -> dict[str, UUID]:
    classes = await graphql_client._testing__get_primary_types()
    result: dict[str, UUID] = {}
    for obj in classes.objects:
        for validity in obj.validities:
            result[validity.user_key] = validity.uuid
    logger.info("got primary types", types=result)
    return result


# TODO(#70977): rewrite in next commit to return `MoraHelper` shim, rather than the real `MoraHelper`
@pytest.fixture
async def mora_helper() -> MoraHelper:
    settings = Settings()
    return MoraHelper(
        hostname=settings.fastramqpi.mo_url,
        auth_server=settings.fastramqpi.auth_server,
        client_id=settings.fastramqpi.client_id,
        client_secret=settings.fastramqpi.client_secret.get_secret_value(),
        auth_realm=settings.fastramqpi.auth_realm,
        use_cache=False,
    )
