# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import uuid
from datetime import datetime
from uuid import UUID

import pytest
from fastramqpi.pytest_util import retry
from fastramqpi.pytest_util import stop_after_delay
from more_itertools import one
from zoneinfo import ZoneInfo

from calculate_primary.autogenerated_graphql_client import EngagementCreateInput
from calculate_primary.autogenerated_graphql_client import GraphQLClient
from calculate_primary.autogenerated_graphql_client import RAValidityInput
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)


def _engagement_input(
    *,
    person: UUID,
    org_unit: UUID,
    user_key: str,
    primary: UUID | None,
) -> EngagementCreateInput:
    tz = ZoneInfo("Europe/Copenhagen")
    start = datetime(1970, 1, 1, tzinfo=tz)
    return EngagementCreateInput(
        validity=RAValidityInput(from_=start),
        org_unit=org_unit,
        engagement_type=uuid.uuid4(),
        job_function=uuid.uuid4(),
        person=person,
        user_key=user_key,
        primary=primary,
    )


async def _fetch_engagement(graphql_client: GraphQLClient, engagement_uuid: UUID):
    engagements = await graphql_client.get_engagements([engagement_uuid])
    obj = one(engagements.objects)
    return one(obj.validities)


@pytest.mark.integration_test
async def test_single_engagement(
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
    primary_types: dict[str, UUID],
):
    """Tests that a single non-primary engagement becomes primary."""

    non_primary = primary_types["non-primary"]
    primary = primary_types["primary"]

    engagement = await graphql_client._testing__create_engagement(
        _engagement_input(
            person=default_employee.uuid,
            org_unit=default_org_unit.uuid,
            user_key="1",
            primary=non_primary,
        )
    )

    @retry(stop=stop_after_delay(30))
    async def verify() -> None:
        validity = await _fetch_engagement(graphql_client, engagement.uuid)
        assert validity.primary is not None
        assert validity.primary.uuid == primary

    await verify()


@pytest.mark.integration_test
async def test_multiple_engagements(
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
    primary_types: dict[str, UUID],
):
    """Tests that when multiple non-primary engagements are present, only one
    becomes primary."""

    non_primary = primary_types["non-primary"]
    primary = primary_types["primary"]

    engagement_1 = await graphql_client._testing__create_engagement(
        _engagement_input(
            person=default_employee.uuid,
            org_unit=default_org_unit.uuid,
            user_key="1",
            primary=non_primary,
        )
    )
    engagement_2 = await graphql_client._testing__create_engagement(
        _engagement_input(
            person=default_employee.uuid,
            org_unit=default_org_unit.uuid,
            user_key="2",
            primary=non_primary,
        )
    )

    @retry(stop=stop_after_delay(30))
    async def verify() -> None:
        v1 = await _fetch_engagement(graphql_client, engagement_1.uuid)
        v2 = await _fetch_engagement(graphql_client, engagement_2.uuid)
        assert v1.primary is not None
        assert v1.primary.uuid == non_primary
        assert v2.primary is not None
        assert v2.primary.uuid == primary

    await verify()


@pytest.mark.integration_test
async def test_idempotency(
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
    primary_types: dict[str, UUID],
):
    """Tests that when multiple engagements are present, and the first is already
    primary, nothing happens."""

    non_primary = primary_types["non-primary"]
    primary = primary_types["primary"]

    engagement_1 = await graphql_client._testing__create_engagement(
        _engagement_input(
            person=default_employee.uuid,
            org_unit=default_org_unit.uuid,
            user_key="1",
            primary=non_primary,
        )
    )
    engagement_2 = await graphql_client._testing__create_engagement(
        _engagement_input(
            person=default_employee.uuid,
            org_unit=default_org_unit.uuid,
            user_key="2",
            primary=primary,
        )
    )

    @retry(stop=stop_after_delay(30))
    async def verify() -> None:
        v1 = await _fetch_engagement(graphql_client, engagement_1.uuid)
        v2 = await _fetch_engagement(graphql_client, engagement_2.uuid)
        assert v1.primary is not None
        assert v1.primary.uuid == non_primary
        assert v2.primary is not None
        assert v2.primary.uuid == primary

    await verify()


@pytest.mark.integration_test
async def test_swap_primaries(
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
    primary_types: dict[str, UUID],
):
    """Tests that when a primary and non-primary engagements exist, but in the
    wrong order, they swap."""

    non_primary = primary_types["non-primary"]
    primary = primary_types["primary"]

    engagement_1 = await graphql_client._testing__create_engagement(
        _engagement_input(
            person=default_employee.uuid,
            org_unit=default_org_unit.uuid,
            user_key="1",
            primary=primary,
        )
    )
    engagement_2 = await graphql_client._testing__create_engagement(
        _engagement_input(
            person=default_employee.uuid,
            org_unit=default_org_unit.uuid,
            user_key="2",
            primary=non_primary,
        )
    )

    @retry(stop=stop_after_delay(30))
    async def verify() -> None:
        v1 = await _fetch_engagement(graphql_client, engagement_1.uuid)
        v2 = await _fetch_engagement(graphql_client, engagement_2.uuid)
        assert v1.primary is not None
        assert v1.primary.uuid == non_primary
        assert v2.primary is not None
        assert v2.primary.uuid == primary

    await verify()


@pytest.mark.integration_test
async def test_fixed_primary(
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
    primary_types: dict[str, UUID],
):
    """Tests that fixed primary overrides normal primary assignment order."""

    non_primary = primary_types["non-primary"]
    fixed_primary = primary_types["explicitly-primary"]

    engagement_1 = await graphql_client._testing__create_engagement(
        _engagement_input(
            person=default_employee.uuid,
            org_unit=default_org_unit.uuid,
            user_key="1",
            primary=fixed_primary,
        )
    )
    engagement_2 = await graphql_client._testing__create_engagement(
        _engagement_input(
            person=default_employee.uuid,
            org_unit=default_org_unit.uuid,
            user_key="2",
            primary=primary_types["primary"],
        )
    )

    @retry(stop=stop_after_delay(30))
    async def verify() -> None:
        v1 = await _fetch_engagement(graphql_client, engagement_1.uuid)
        v2 = await _fetch_engagement(graphql_client, engagement_2.uuid)
        assert v1.primary is not None
        assert v1.primary.uuid == fixed_primary
        assert v2.primary is not None
        assert v2.primary.uuid == non_primary

    await verify()
