# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import uuid
from datetime import datetime
from uuid import UUID

import pytest
from fastramqpi.pytest_util import retry
from fastramqpi.pytest_util import stop_after_delay
from httpx import AsyncClient
from more_itertools import one
from zoneinfo import ZoneInfo

from calculate_primary.autogenerated_graphql_client import EngagementCreateInput
from calculate_primary.autogenerated_graphql_client import GraphQLClient
from calculate_primary.autogenerated_graphql_client import RAValidityInput
from calculate_primary.autogenerated_graphql_client import TestingCreateClassClassCreate
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)


@pytest.mark.integration_test
@pytest.mark.envvar({"DELAY_EVENT": "1"})
@pytest.mark.parametrize(
    "primary_class_user_key",
    [
        pytest.param(
            "primary",
            id="default",
            marks=pytest.mark.envvar({"INTEGRATION": "DEFAULT"}),
        ),
        pytest.param(
            "Ansat",
            id="sd",
            marks=pytest.mark.envvar({"INTEGRATION": "SD"}),
        ),
        pytest.param(
            "primary",
            id="opus",
            marks=pytest.mark.envvar({"INTEGRATION": "OPUS"}),
        ),
    ],
)
async def test_single_engagement(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
    default_engagement_type: TestingCreateClassClassCreate,
    primary_types: dict[str, UUID],
    primary_class_user_key: str,
) -> None:
    """
    Tests that a single non-primary engagement becomes primary.

    Note that in `SD` mode, the `user_key` for the primary class is `Ansat`
    instead of `primary`.
    """

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(2020, 1, 1, tzinfo=tz)
    non_primary = primary_types["non-primary"]
    primary = primary_types[primary_class_user_key]

    engagement = await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t0),
            org_unit=default_org_unit.uuid,
            engagement_type=default_engagement_type.uuid,
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
            primary=non_primary,
        )
    )

    @retry(stop=stop_after_delay(30))
    async def verify() -> None:
        engagements = await graphql_client._testing__get_engagement(engagement.uuid)
        obj = one(engagements.objects)
        validity = one(obj.validities)

        assert validity.primary_response is not None
        primary_response = one(validity.primary_response.validities)

        assert primary_response.uuid == primary

    await verify()


@pytest.mark.integration_test
@pytest.mark.envvar({"DELAY_EVENT": "1"})
@pytest.mark.parametrize(
    "primary_class_user_key,highest_user_key_wins",
    [
        pytest.param(
            "primary",
            True,
            id="default",
            marks=pytest.mark.envvar({"INTEGRATION": "DEFAULT"}),
        ),
        pytest.param(
            "Ansat",
            False,
            id="sd",
            marks=pytest.mark.envvar({"INTEGRATION": "SD"}),
        ),
        pytest.param(
            "primary",
            False,
            id="opus",
            marks=pytest.mark.envvar({"INTEGRATION": "OPUS"}),
        ),
    ],
)
async def test_multiple_engagements(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
    default_engagement_type: TestingCreateClassClassCreate,
    primary_types: dict[str, UUID],
    primary_class_user_key: str,
    highest_user_key_wins: bool,
) -> None:
    """Tests that when multiple non-primary engagements are present, only one
    becomes primary."""

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(2020, 1, 1, tzinfo=tz)
    non_primary = primary_types["non-primary"]
    primary = primary_types[primary_class_user_key]

    engagement_1 = await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t0),
            org_unit=default_org_unit.uuid,
            engagement_type=default_engagement_type.uuid,
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
            primary=non_primary,
            user_key="333",
        )
    )
    engagement_2 = await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t0),
            org_unit=default_org_unit.uuid,
            engagement_type=default_engagement_type.uuid,
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
            primary=non_primary,
            user_key="777",
        )
    )

    @retry(stop=stop_after_delay(30))
    async def verify() -> None:
        engagements = await graphql_client._testing__get_engagement(engagement_1.uuid)
        obj = one(engagements.objects)
        v1 = one(obj.validities)

        assert v1.primary_response is not None
        p1 = one(v1.primary_response.validities)

        engagements = await graphql_client._testing__get_engagement(engagement_2.uuid)
        obj = one(engagements.objects)
        v2 = one(obj.validities)

        assert v2.primary_response is not None
        p2 = one(v2.primary_response.validities)

        assert v1.fraction is None
        assert v2.fraction is None

        # which one becomes primary depends on the integration's tie-breaking logic,
        # which is different for each integration.
        # - SD and OPUS tie-break by lowest user key (333)
        # - DEFAULT time-breaks highest user key (777)
        if highest_user_key_wins:
            assert p1.uuid == non_primary
            assert p2.uuid == primary
        else:
            assert p1.uuid == primary
            assert p2.uuid == non_primary

    await verify()
