# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0


import uuid
from datetime import datetime
from datetime import timedelta
from uuid import UUID

import pytest
import structlog
from more_itertools import one
from zoneinfo import ZoneInfo

from calculate_primary.autogenerated_graphql_client import ClassCreateInput
from calculate_primary.autogenerated_graphql_client import EngagementCreateInput
from calculate_primary.autogenerated_graphql_client import FacetCreateInput
from calculate_primary.autogenerated_graphql_client import RAValidityInput
from calculate_primary.autogenerated_graphql_client import TestingCreateClassClassCreate
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)
from calculate_primary.autogenerated_graphql_client.client import GraphQLClient
from calculate_primary.model import ClassDict
from calculate_primary.model import EngagementDict
from calculate_primary.model import EngagementEditPayload
from calculate_primary.mora_helper_shim import MoraHelper

logger = structlog.stdlib.get_logger()


@pytest.mark.integration_test
@pytest.mark.envvar({"INTEGRATION": "DEFAULT", "DELAY_AMQP": "1"})
async def test_read_user_engagements(
    mora_helper: MoraHelper,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
    primary_types: dict[str, UUID],
    default_engagement_type: TestingCreateClassClassCreate,
) -> None:
    """
    Test that `MoraHelper.read_user_engagements` returns data in the expected format.

    Sets up the following engagements:
    ```
    time:   t0    t1    t2    t3    t4
    e1:     |-----------|     :
    e2:           |-----------:-----|
    e3:                 |-----:----------->
                              :
                              at
    ```

    `read_user_engagements` should return the list [e2, e3]
    """

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(2020, 1, 1, tzinfo=tz)
    t1 = datetime(2021, 1, 1, tzinfo=tz)
    t2 = datetime(2022, 1, 1, tzinfo=tz)
    t3 = datetime(2023, 1, 1, tzinfo=tz)
    t4 = datetime(2024, 1, 1, tzinfo=tz)
    uk2 = "principal aqueduct mechanist"
    uk3 = "coin stamper"
    primary = primary_types["primary"]
    non_primary = primary_types["non-primary"]

    await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            # XXX: this repo is stuck on v22 of the GraphQL API, which has off-by-one
            #   semantics on validities
            validity=RAValidityInput(from_=t0, to=t2 - timedelta(days=1)),
            org_unit=default_org_unit.uuid,
            engagement_type=default_engagement_type.uuid,
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
        )
    )
    e2 = await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t1, to=t4 - timedelta(days=1)),
            org_unit=default_org_unit.uuid,
            engagement_type=default_engagement_type.uuid,
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
            user_key=uk2,
            primary=non_primary,
        )
    )
    e3 = await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t2),
            org_unit=default_org_unit.uuid,
            engagement_type=default_engagement_type.uuid,
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
            user_key=uk3,
            primary=primary,
        )
    )

    engs: list[EngagementDict] = mora_helper.read_user_engagements(
        default_employee.uuid,
        at=t3,
        only_primary=True,
        use_cache=False,
    )
    engs = sorted(engs, key=lambda eng: eng["validity"]["from"])
    logger.info("got engagements", engagements=engs)

    got_e2, got_e3 = engs
    assert got_e2["uuid"] == str(e2.uuid)
    assert got_e2["user_key"] == uk2
    assert got_e2["primary"] is not None
    assert got_e2["primary"]["uuid"] == str(non_primary)
    assert got_e2["fraction"] is None

    assert got_e3["uuid"] == str(e3.uuid)
    assert got_e3["user_key"] == uk3
    assert got_e3["primary"] is not None
    assert got_e3["primary"]["uuid"] == str(primary)
    assert got_e3["fraction"] is None


@pytest.mark.integration_test
@pytest.mark.envvar({"INTEGRATION": "DEFAULT", "DELAY_AMQP": "1"})
async def test_find_cut_dates(
    mora_helper: MoraHelper,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
    default_engagement_type: TestingCreateClassClassCreate,
) -> None:
    """
    Test that `MoraHelper.find_cut_dates` returns data in the expected format.

    Sets up the following engagements:
    ```
    time:   t0    t1    t2    t3
    e1:     |-----------|
    e2:           |-----------|
    ```

    `find_cut_dates` should return the list [t0, t1, t2, t4]
    """

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(2020, 1, 1, tzinfo=tz)
    t1 = datetime(2021, 1, 1, tzinfo=tz)
    t2 = datetime(2022, 1, 1, tzinfo=tz)
    t3 = datetime(2023, 1, 1, tzinfo=tz)

    await graphql_client._testing__create_engagement(
        # XXX: this repo is stuck on v22 of the GraphQL API, which has off-by-one
        #   semantics on validities
        EngagementCreateInput(
            validity=RAValidityInput(from_=t0, to=t2 - timedelta(days=1)),
            org_unit=default_org_unit.uuid,
            engagement_type=default_engagement_type.uuid,
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
        )
    )
    await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t1, to=t3 - timedelta(days=1)),
            org_unit=default_org_unit.uuid,
            engagement_type=default_engagement_type.uuid,
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
        )
    )

    dates = mora_helper.find_cut_dates(str(default_employee.uuid))

    # XXX: `MoraHelper` returns naive datetimes, so we have to strip the timezone
    #   before asserting
    assert dates == [
        t0.replace(tzinfo=None),
        t1.replace(tzinfo=None),
        t2.replace(tzinfo=None),
        t3.replace(tzinfo=None),
    ]


@pytest.mark.integration_test
@pytest.mark.envvar({"INTEGRATION": "DEFAULT", "DELAY_AMQP": "1"})
async def test_mo_post(
    mora_helper: MoraHelper,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
    primary_types: dict[str, UUID],
    default_engagement_type: TestingCreateClassClassCreate,
) -> None:
    """
    Test that `MoraHelper._mo_post("details/edit", payload)` behaves as expected.

    We create an engagement without a primary, then we edit it to give it a primary
    field in a specific validity.

    We assert that we have three validities after the edit: one before the edit,
    one containing the edit, and one after the edit.
    """

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(2020, 1, 1, tzinfo=tz)
    t1 = datetime(2021, 1, 1, tzinfo=tz)
    t2 = datetime(2022, 1, 1, tzinfo=tz)
    primary = primary_types["primary"]
    engagement_before = await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t0),
            org_unit=default_org_unit.uuid,
            engagement_type=default_engagement_type.uuid,
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
        )
    )

    payload: EngagementEditPayload = {
        "type": "engagement",
        "uuid": str(engagement_before.uuid),
        "data": {
            "validity": {
                # MoraHelper expects naive date strings, not full datetimes
                "from": t1.date().isoformat(),
                "to": (t2 - timedelta(days=1)).date().isoformat(),
            },
            "primary": {"uuid": str(primary)},
        },
    }
    res = mora_helper._mo_post("details/edit", payload)
    res.raise_for_status()

    engagements = await graphql_client._testing__get_employee_engagements(
        default_employee.uuid
    )
    obj = one(engagements.objects)
    validities = sorted(obj.validities, key=lambda eng: eng.validity.from_)
    e0, e1, e2 = validities

    # engagement has no primary in the interval [t0, t1)
    assert e0.uuid == engagement_before.uuid
    assert e0.validity.from_ == t0
    assert e0.validity.to == t1 - timedelta(days=1)
    assert e0.primary_response is None

    # engagement has a primary "primary" in the interval [t1, t2)
    assert e1.uuid == engagement_before.uuid
    assert e1.validity.from_ == t1
    assert e1.validity.to == t2 - timedelta(days=1)
    p1 = e1.primary_response
    assert p1 is not None
    assert one(p1.validities).uuid == primary

    # engagement has no primary in the interval [t2, ...)
    assert e2.uuid == engagement_before.uuid
    assert e2.validity.from_ == t2
    assert e2.validity.to is None
    assert e2.primary_response is None


@pytest.mark.integration_test
@pytest.mark.envvar({"INTEGRATION": "DEFAULT", "DELAY_AMQP": "1"})
async def test_read_classes_in_facet(
    mora_helper: MoraHelper,
    graphql_client: GraphQLClient,
) -> None:
    """Test that `MoraHelper.read_classes_in_facet` returns data in the expected format."""

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(2020, 1, 1, tzinfo=tz)

    facet = await graphql_client._testing__create_facet(
        FacetCreateInput(
            user_key="favorite_pokemon", validity=RAValidityInput(from_=t0)
        )
    )

    klass = await graphql_client._testing__create_class(
        ClassCreateInput(
            name="Snorlax",
            user_key="Snorlax",
            facet_uuid=facet.uuid,
            validity=RAValidityInput(from_=t0),
        )
    )

    classes, facet_uuid = mora_helper.read_classes_in_facet("favorite_pokemon")

    got_class: ClassDict = one(classes)
    assert facet_uuid == str(facet.uuid)
    assert got_class["user_key"] == "Snorlax"
    assert got_class["uuid"] == str(klass.uuid)


@pytest.mark.integration_test
@pytest.mark.envvar({"INTEGRATION": "DEFAULT", "DELAY_AMQP": "1"})
async def test_mo_post_error_400(
    mora_helper: MoraHelper,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
    primary_types: dict[str, UUID],
    default_engagement_type: TestingCreateClassClassCreate,
) -> None:
    """
    Tests that an error 400 is raised if a complete but invalid payload is sent
    to `_mo_post`. The payload contains an invalid validity.
    """

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(2020, 1, 1, tzinfo=tz)
    t1 = datetime(2021, 1, 1, tzinfo=tz)
    engagement = await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t0),
            org_unit=default_org_unit.uuid,
            engagement_type=default_engagement_type.uuid,
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
        )
    )

    payload: EngagementEditPayload = {
        "type": "engagement",
        "uuid": str(engagement.uuid),
        "data": {
            "validity": {
                # this is deliberately wrong: from is after to
                "from": t1.date().isoformat(),
                "to": t0.date().isoformat(),
            },
            "primary": {"uuid": str(primary_types["primary"])},
        },
    }
    res = mora_helper._mo_post("details/edit", payload)
    assert res.status_code == 400
