# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

# TODO(#70977): re-write these in next commit to target `MoraHelper` shim


import pytest
from fastramqpi.autogenerated_graphql_client.client import GraphQLClient
from os2mo_helpers.mora_helpers import MoraHelper


@pytest.mark.integration_test
async def test_read_user_engagements(
    mora_helper: MoraHelper, graphql_client: GraphQLClient
):
    pass
