# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import uuid
from datetime import datetime
from uuid import UUID

import pytest
from fastramqpi.pytest_util import retry
from fastramqpi.pytest_util import stop_after_delay
from httpx import AsyncClient
from more_itertools import one
from zoneinfo import ZoneInfo

from calculate_primary.autogenerated_graphql_client import EngagementCreateInput
from calculate_primary.autogenerated_graphql_client import GraphQLClient
from calculate_primary.autogenerated_graphql_client import RAValidityInput
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from calculate_primary.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)


@pytest.mark.integration_test
@pytest.mark.envvar({"INTEGRATION": "DEFAULT", "DELAY_AMQP": "1"})
async def test_single_engagement(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
    primary_types: dict[str, UUID],
):
    """Tests that a single non-primary engagement becomes primary."""

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(2020, 1, 1, tzinfo=tz)
    non_primary = primary_types["non-primary"]
    primary = primary_types["primary"]

    engagement = await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t0),
            org_unit=default_org_unit.uuid,
            engagement_type=uuid.uuid4(),
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
            primary=non_primary,
        )
    )

    @retry(stop=stop_after_delay(30))
    async def verify() -> None:
        engagements = await graphql_client._testing__get_engagements([engagement.uuid])
        obj = one(engagements.objects)
        validity = one(obj.validities)
        assert validity.primary is not None
        assert validity.primary.uuid == primary

    await verify()


@pytest.mark.integration_test
@pytest.mark.envvar({"INTEGRATION": "DEFAULT", "DELAY_AMQP": "1"})
async def test_multiple_engagements(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
    primary_types: dict[str, UUID],
):
    """Tests that when multiple non-primary engagements are present, only one
    becomes primary."""

    tz = ZoneInfo("Europe/Copenhagen")
    t0 = datetime(2020, 1, 1, tzinfo=tz)
    non_primary = primary_types["non-primary"]
    primary = primary_types["primary"]

    engagement_1 = await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t0),
            org_unit=default_org_unit.uuid,
            engagement_type=uuid.uuid4(),
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
            primary=non_primary,
        )
    )
    engagement_2 = await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t0),
            org_unit=default_org_unit.uuid,
            engagement_type=uuid.uuid4(),
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
            primary=non_primary,
        )
    )

    @retry(stop=stop_after_delay(30))
    async def verify() -> None:
        engagements = await graphql_client._testing__get_engagements(
            [engagement_1.uuid]
        )
        obj = one(engagements.objects)
        v1 = one(obj.validities)
        engagements = await graphql_client._testing__get_engagements(
            [engagement_2.uuid]
        )
        obj = one(engagements.objects)
        v2 = one(obj.validities)
        assert v1.primary is not None
        assert v2.primary is not None

        # exactly which of the two becomes the primary is not important, just
        # check that there is one primary and one non-primary
        uuids = {v1.primary.uuid, v2.primary.uuid}
        assert primary in uuids
        assert non_primary in uuids

    await verify()
