# Generated by ariadne-codegen on 2026-07-21 10:57
# Source: queries.graphql

from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class TestingGetEngagements(BaseModel):
    engagements: "TestingGetEngagementsEngagements"


class TestingGetEngagementsEngagements(BaseModel):
    objects: List["TestingGetEngagementsEngagementsObjects"]


class TestingGetEngagementsEngagementsObjects(BaseModel):
    validities: List["TestingGetEngagementsEngagementsObjectsValidities"]


class TestingGetEngagementsEngagementsObjectsValidities(BaseModel):
    uuid: UUID
    user_key: str
    is_primary: bool
    primary: Optional["TestingGetEngagementsEngagementsObjectsValiditiesPrimary"]


class TestingGetEngagementsEngagementsObjectsValiditiesPrimary(BaseModel):
    uuid: UUID
    user_key: str


TestingGetEngagements.update_forward_refs()
TestingGetEngagementsEngagements.update_forward_refs()
TestingGetEngagementsEngagementsObjects.update_forward_refs()
TestingGetEngagementsEngagementsObjectsValidities.update_forward_refs()
TestingGetEngagementsEngagementsObjectsValiditiesPrimary.update_forward_refs()
