# Generated by ariadne-codegen on 2026-07-20 11:56
# Source: queries.graphql

from typing import List
from uuid import UUID

from .base_model import BaseModel


class GetPrimaryTypes(BaseModel):
    classes: "GetPrimaryTypesClasses"


class GetPrimaryTypesClasses(BaseModel):
    objects: List["GetPrimaryTypesClassesObjects"]


class GetPrimaryTypesClassesObjects(BaseModel):
    validities: List["GetPrimaryTypesClassesObjectsValidities"]


class GetPrimaryTypesClassesObjectsValidities(BaseModel):
    uuid: UUID
    user_key: str


GetPrimaryTypes.update_forward_refs()
GetPrimaryTypesClasses.update_forward_refs()
GetPrimaryTypesClassesObjects.update_forward_refs()
GetPrimaryTypesClassesObjectsValidities.update_forward_refs()
