# Generated by ariadne-codegen on 2026-07-20 11:56
# Source: queries.graphql

from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class GetEngagements(BaseModel):
    engagements: "GetEngagementsEngagements"


class GetEngagementsEngagements(BaseModel):
    objects: List["GetEngagementsEngagementsObjects"]


class GetEngagementsEngagementsObjects(BaseModel):
    validities: List["GetEngagementsEngagementsObjectsValidities"]


class GetEngagementsEngagementsObjectsValidities(BaseModel):
    uuid: UUID
    user_key: str
    is_primary: bool
    primary: Optional["GetEngagementsEngagementsObjectsValiditiesPrimary"]


class GetEngagementsEngagementsObjectsValiditiesPrimary(BaseModel):
    uuid: UUID
    user_key: str


GetEngagements.update_forward_refs()
GetEngagementsEngagements.update_forward_refs()
GetEngagementsEngagementsObjects.update_forward_refs()
GetEngagementsEngagementsObjectsValidities.update_forward_refs()
GetEngagementsEngagementsObjectsValiditiesPrimary.update_forward_refs()
