# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from datetime import datetime
from datetime import timedelta
from typing import Literal
from uuid import UUID

from httpx import Response
from more_itertools import first

from calculate_primary.autogenerated_graphql_client import EngagementUpdateInput
from calculate_primary.autogenerated_graphql_client import (
    GetEmployeeEngagementsAtEngagementsObjectsCurrent,
)
from calculate_primary.autogenerated_graphql_client import GraphQLClient
from calculate_primary.autogenerated_graphql_client import (
    GraphQLClientGraphQLMultiError,
)
from calculate_primary.autogenerated_graphql_client import RAValidityInput
from calculate_primary.model import ClassDict
from calculate_primary.model import EngagementDict
from calculate_primary.model import EngagementEditPayload
from calculate_primary.model import EngagementPrimaryDict
from calculate_primary.model import EngagementTypeDict


class MoraHelper:
    _gql_client: GraphQLClient

    def __init__(self, gql_client: GraphQLClient):
        self._gql_client = gql_client

    async def read_user_engagements(
        self,
        user: UUID | str,
        at: datetime,
        only_primary: Literal[True],
        use_cache: Literal[False],
    ) -> list[EngagementDict]:
        assert only_primary, "`only_primary=False` is not supported by this shim"
        assert not use_cache, "`use_cache=True` is not supported by this shim"

        employee_uuid = user if isinstance(user, UUID) else UUID(user)
        res = await self._gql_client.get_employee_engagements_at(
            uuid=employee_uuid, at=at
        )
        return [
            _gql_engagement_to_service_engagement(obj.current)
            for obj in res.objects
            if obj.current is not None
        ]

    async def find_cut_dates(
        self, uuid: str, no_past: Literal[False] = False
    ) -> list[datetime]:
        assert not no_past, "`no_past=True` is not supported by this shim"

        res = await self._gql_client.get_employee_engagements(UUID(uuid))
        validities = (
            validity.validity for obj in res.objects for validity in obj.validities
        )
        dates: set[datetime] = set()
        for validity in validities:
            dates.add(validity.from_)
            if to := validity.to:
                # XXX: correct off-by-one due to GraphQL API v22
                dates.add(to + timedelta(days=1))
            else:
                dates.add(datetime(9999, 12, 30, 0, 0))
        dates_naive = (
            # XXX: throwing away tzinfo for compatibility
            date.replace(hour=0, minute=0, second=0, microsecond=0, tzinfo=None)
            for date in dates
        )
        return sorted(dates_naive)

    async def _mo_post(
        self, url: Literal["details/edit"], payload: EngagementEditPayload
    ) -> Response:
        assert url == "details/edit", f"`url={url}` is not supported by this shim"
        assert (
            payload["type"] == "engagement"
        ), "editing types other than `engagement` is not supported by this shim"

        uuid = UUID(payload["uuid"])
        from_ = datetime.strptime(payload["data"]["validity"]["from"], "%Y-%m-%d")
        to = None
        if to_str := payload["data"]["validity"]["to"]:
            to = datetime.strptime(to_str, "%Y-%m-%d")
        primary = UUID(payload["data"]["primary"]["uuid"])

        try:
            res = await self._gql_client.update_engagement(
                EngagementUpdateInput(
                    uuid=uuid,
                    validity=RAValidityInput(from_=from_, to=to),
                    primary=primary,
                )
            )

        # service API returns status 400 for a variety of validation errors, the
        # call site actually checks if status code is 400 and handles them differently,
        # so we have to map client errors to 400
        except GraphQLClientGraphQLMultiError as e:
            return Response(status_code=400, content=str(e))

        # we let other exceptions through, as the call site only checks for 400
        # and 200 explicitly

        # sanity check
        assert res.uuid == uuid

        # call sites expect a success response, so we fake one.
        return Response(status_code=200)

    async def read_classes_in_facet(self, facet: str) -> tuple[list[ClassDict], str]:
        res = await self._gql_client.get_facet_classes_by_user_key(facet)
        classes: list[ClassDict] = [
            {"user_key": validity.user_key, "uuid": str(validity.uuid)}
            for obj in res.classes.objects
            for validity in obj.validities
        ]
        facets = (
            str(validity.uuid)
            for obj in res.facets.objects
            for validity in obj.validities
        )

        # graphql may return multiple facets for a given user key, because
        # user keys aren't unique and because bitemporality. Instead of returning
        # a random UUID, we assert that they are all the same.
        facet_uuid = first(facets)
        assert all(
            facet == facet_uuid for facet in facets
        ), "facet user_key to UUID mapping is ambiguous"

        return (classes, facet_uuid)


def _gql_engagement_to_service_engagement(
    eng: GetEmployeeEngagementsAtEngagementsObjectsCurrent,
) -> EngagementDict:
    uuid = str(eng.uuid)
    user_key = eng.user_key
    fraction = eng.fraction
    engagement_type_current = eng.engagement_type_response.current
    assert engagement_type_current is not None
    engagement_type: EngagementTypeDict = {"uuid": str(engagement_type_current.uuid)}
    primary: EngagementPrimaryDict | None
    if (res := eng.primary_response) and (current := res.current):
        primary = {"uuid": str(current.uuid)}
    else:
        primary = None

    # XXX: throwing away tzinfo for compatibility
    validity_from = eng.validity.from_.strftime("%Y-%m-%d")
    if to := eng.validity.to:
        validity_to = to.strftime("%Y-%m-%d")
    else:
        validity_to = None

    return {
        "uuid": uuid,
        "user_key": user_key,
        "fraction": fraction,
        "engagement_type": engagement_type,
        "primary": primary,
        "validity": {"from": validity_from, "to": validity_to},
    }
